'use strict';

/**
 * provisioner.js — Visual Infrastructure Provisioner
 *
 * Translates a Ghostwire DAG into a real Docker Compose stack.
 * Infrastructure nodes (postgres, redis, nginx) are mapped to real containers.
 * All Docker CLI output is streamed back to connected clients via WebSocket.
 */

const { spawn } = require('child_process');
const fs        = require('fs');
const path      = require('path');

const STACK_DIR = path.join(process.cwd(), '.ghostwire-stack');

// ── Node type → Docker service template ───────────────────────────────────────

const SERVICE_TEMPLATES = {
  postgres: (node) => ({
    service: `  ${node._svcName}:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ghostwire
      POSTGRES_PASSWORD: ghostwire_secret
      POSTGRES_DB: pipeline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ghostwire"]
      interval: 10s
      timeout: 5s
      retries: 5`,
    volume: 'postgres_data:',
    type: 'postgres',
  }),

  redis: (node) => ({
    service: `  ${node._svcName}:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5`,
    volume: 'redis_data:',
    type: 'redis',
  }),

  nginx: (node) => ({
    service: `  ${node._svcName}:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"`,
    volume: null,
    type: 'nginx',
  }),
};

// ── NGINX config template ─────────────────────────────────────────────────────

const buildNginxConf = () => `
worker_processes auto;
events { worker_connections 1024; }

http {
  upstream ghostwire_backend {
    server host.docker.internal:3001;
  }

  server {
    listen 80;
    server_name _;

    # Proxy all API and WebSocket traffic to the Ghostwire backend
    location /api/ {
      proxy_pass         http://ghostwire_backend;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }

    location /socket.io/ {
      proxy_pass         http://ghostwire_backend;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
      proxy_set_header   Host $host;
    }

    location / {
      return 200 'Ghostwire API Gateway — OK\\n';
      add_header Content-Type text/plain;
    }
  }
}
`.trimStart();

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Derive palette type from either schema format (node.type) or UI format (node.data.paletteType) */
function getNodeType(node) {
  // UI format: { type: 'flowNode', data: { paletteType: '...' } }
  if (node.type === 'flowNode' && node.data?.paletteType) return node.data.paletteType;
  // Schema / YAML format: { type: 'postgres' | 'redis' | ... }
  return node.type ?? '';
}

/** Sanitise a node id into a valid Docker Compose service name */
function toServiceName(nodeId) {
  return (nodeId ?? 'svc').replace(/[^a-z0-9_-]/gi, '-').toLowerCase().slice(0, 40);
}

/** Build annotated node list — attach _svcName so templates are DRY */
function annotateNodes(nodes) {
  return nodes.map(n => ({ ...n, _svcName: toServiceName(n.id), _type: getNodeType(n) }));
}

// ── Compose file generator ────────────────────────────────────────────────────

/**
 * Generates docker-compose.yml and (optionally) nginx.conf.
 * Returns null if no infra nodes are present.
 */
function generateStack(nodes) {
  const annotated = annotateNodes(nodes);
  const infraNodes = annotated.filter(n => SERVICE_TEMPLATES[n._type]);

  if (infraNodes.length === 0) return null;

  const services = [];
  const volumes  = new Set();
  let   hasNginx = false;

  for (const node of infraNodes) {
    const tmpl = SERVICE_TEMPLATES[node._type](node);
    services.push(tmpl.service);
    if (tmpl.volume) volumes.add(tmpl.volume);
    if (tmpl.type === 'nginx') hasNginx = true;
  }

  const volBlock = volumes.size > 0
    ? `\nvolumes:\n  ${[...volumes].join('\n  ')}\n`
    : '';

  const compose = [
    '# Auto-generated by Ghostwire Visual Infrastructure Provisioner',
    '# Re-generated on every deploy — do not edit manually',
    '',
    'services:',
    ...services.map(s => s + '\n'),
    volBlock,
  ].join('\n');

  return { compose, hasNginx, infraNodes };
}

/** Write the stack files to .ghostwire-stack/ */
function writeStackFiles(nodes) {
  const result = generateStack(nodes);
  if (!result) return null;

  if (!fs.existsSync(STACK_DIR)) fs.mkdirSync(STACK_DIR, { recursive: true });
  fs.writeFileSync(path.join(STACK_DIR, 'docker-compose.yml'), result.compose, 'utf-8');
  if (result.hasNginx) {
    fs.writeFileSync(path.join(STACK_DIR, 'nginx.conf'), buildNginxConf(), 'utf-8');
  }

  return result;
}

// ── Docker executor ───────────────────────────────────────────────────────────

/**
 * Run docker compose up -d --remove-orphans.
 * All stdout/stderr is emitted as 'docker_provision_log' WebSocket events.
 * Returns a Promise<{ code, error }> — never rejects.
 */
function runProvision(io, nodes) {
  const emit = (stream, text) => {
    io.emit('docker_provision_log', { stream, text, ts: new Date().toISOString() });
  };

  // ── Write compose file ──────────────────────────────────────────────────────
  let stack;
  try {
    stack = writeStackFiles(nodes);
  } catch (err) {
    emit('error', `✗ Failed to write compose file: ${err.message}`);
    return Promise.resolve({ code: -1, error: true });
  }

  if (!stack) {
    emit('info', '⊘  No infrastructure nodes (postgres / redis / nginx) detected — skipping Docker provisioning.');
    return Promise.resolve({ skipped: true });
  }

  const serviceNames = stack.infraNodes.map(n => `${n._type}:${n._svcName}`).join(', ');
  emit('info', '');
  emit('info', '╔══════════════════════════════════════════════════════════╗');
  emit('info', '║        🐳  Ghostwire Infrastructure Provisioner          ║');
  emit('info', '╚══════════════════════════════════════════════════════════╝');
  emit('info', '');
  emit('info', `Stack dir : ${STACK_DIR}`);
  emit('info', `Services  : ${serviceNames}`);
  if (stack.hasNginx) emit('info', 'Gateway   : NGINX reverse proxy → port 8080');
  emit('info', '');
  emit('info', 'Running: docker compose up -d --remove-orphans');
  emit('info', '');

  // ── Spawn docker compose ────────────────────────────────────────────────────
  return new Promise((resolve) => {
    let proc;
    try {
      proc = spawn(
        'docker',
        ['compose', '-f', path.join(STACK_DIR, 'docker-compose.yml'), 'up', '-d', '--remove-orphans'],
        { env: process.env, stdio: ['ignore', 'pipe', 'pipe'] },
      );
    } catch (spawnErr) {
      emit('error', `✗ Could not spawn docker: ${spawnErr.message}`);
      emit('error', '  Make sure Docker Desktop (or Docker Engine) is installed and running.');
      return resolve({ code: -1, error: true });
    }

    const splitLines = (data, stream) => {
      for (const raw of data.toString().split('\n')) {
        const line = raw.trimEnd();
        if (!line) continue;
        // Docker routes progress/info to stderr — detect real errors
        const isRealError = stream === 'stderr' && /\berror\b|\bfailed\b|\bcannot\b|\bconflict\b/i.test(line);
        emit(isRealError ? 'error' : stream, line);
      }
    };

    proc.stdout.on('data', (data) => splitLines(data, 'stdout'));
    proc.stderr.on('data', (data) => splitLines(data, 'stderr'));

    proc.on('close', (code) => {
      emit('info', '');
      if (code === 0) {
        emit('success', '✓  Stack is up and healthy.');
        emit('success', `   Provisioned: ${serviceNames}`);
        if (stack.hasNginx) emit('success', '   NGINX gateway → http://localhost:8080');
        emit('info', '');
        resolve({ code, error: false });
      } else {
        emit('error', `✗  docker compose exited with code ${code}.`);
        emit('error', '   Check the logs above for details.');
        emit('info', '');
        resolve({ code, error: true });
      }
    });

    proc.on('error', (err) => {
      emit('error', `✗ docker process error: ${err.message}`);
      resolve({ code: -1, error: true });
    });
  });
}

// ── Teardown ──────────────────────────────────────────────────────────────────

/**
 * docker compose down — called on explicit teardown (future use).
 * Not called on normal deploys; --remove-orphans handles removed services.
 */
function teardownStack(io) {
  const emit = (stream, text) => io.emit('docker_provision_log', { stream, text, ts: new Date().toISOString() });

  const composeFile = path.join(STACK_DIR, 'docker-compose.yml');
  if (!fs.existsSync(composeFile)) {
    emit('info', '⊘  No active stack to tear down.');
    return Promise.resolve({ skipped: true });
  }

  emit('warn', '🐳  Tearing down Ghostwire stack...');

  return new Promise((resolve) => {
    const proc = spawn(
      'docker',
      ['compose', '-f', composeFile, 'down', '--remove-orphans'],
      { env: process.env, stdio: ['ignore', 'pipe', 'pipe'] },
    );

    proc.stdout.on('data', (d) => d.toString().split('\n').filter(Boolean).forEach(l => emit('stdout', l)));
    proc.stderr.on('data', (d) => d.toString().split('\n').filter(Boolean).forEach(l => emit('stderr', l)));

    proc.on('close', (code) => {
      emit(code === 0 ? 'success' : 'error', code === 0 ? '✓  Stack torn down.' : `✗  Teardown exited ${code}`);
      resolve({ code });
    });

    proc.on('error', (err) => {
      emit('error', `✗ Teardown error: ${err.message}`);
      resolve({ code: -1 });
    });
  });
}

module.exports = { runProvision, teardownStack, generateStack, writeStackFiles };
